baseURL = 'https://dolezal-photo.github.io/'
languageCode = 'cs-CZ'
defaultContentLanguage = 'cs'
title = 'Doležal Photo'
theme = "gallery"

[params]
  defaultTheme = "light"

  [params.gallery]
    boxSpacing = 16
    targetRowHeight = 500

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "fotky-originaly/nastaveni.json"
    target = "assets/config/nastaveni.json"
